#!/bin/sh

alias lg='lazygit'
alias gp='cd "$(fd . $(cat $HOME/.projects-dir.txt) -t d -d 1 | fzf)"'
alias ls="exa"
alias ll="exa -l"
alias la="exa -la"
alias dots="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias dotsadd='dots add $(dots status -s | cut -d\  -f 3 | fzf)'

alias edot="~/.scripts/edit_dotfile.sh"
alias epdf="~/.scripts/open_pdf.sh"

alias sysupdate="sudo apt update && sudo apt upgrade"
