#!/bin/sh

alias lg='lazygit'
alias gp='cd "$(~/.scripts/get_projects.sh | fzf)"'
alias ls="exa"
alias ll="exa -l"
alias la="exa -la"
alias dots="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias dotsadd='dots add $(dots status -s | cut -d\  -f 3 | fzf -m)'

alias edot="~/.scripts/edit_dotfile.sh"
alias epdf="~/.scripts/open_pdf.sh"

alias lgd="lazygit --git-dir=$HOME/.dotfiles --work-tree=$HOME"
alias sysupdate="sudo apt update && sudo apt upgrade"
